name: Rubocop

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: sudo apt-get install libncursesw5 libncursesw5-dev libncurses5-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
