name: Tests

on: [push, pull_request]

jobs:
  test-ubuntu-ruby26:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nCurses
      run: sudo apt-get install libncursesw5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake

  test-macos-ruby26:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nCurses
      run: brew install ncurses
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
