---
name: Tests

on: [push, pull_request]

jobs:
  # Ruby 2.7
  #
  test-ubuntu-ruby27:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: sudo apt-get install libncursesw5 libncursesw5-dev libncurses5-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          GENERATE_COVERAGE: 1
          TERM: xterm

  test-macos-ruby27:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: brew install ncurses
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          TERM: xterm

  # Ruby 2.6
  #
  test-ubuntu-ruby26:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nCurses
      run: sudo apt-get install libncursesw5 libncursesw5-dev libncurses5-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
      env:
        TERM: xterm

  test-macos-ruby26:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: brew install ncurses
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          TERM: xterm

  # Ruby 2.5
  #
  test-ubuntu-ruby25:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: sudo apt-get install libncursesw5 libncursesw5-dev libncurses5-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          TERM: xterm

  test-macos-ruby25:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nCurses
        run: brew install ncurses
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          TERM: xterm
