name: Test Ruby 2.7

on: [push, pull_request]

jobs:
  test-ubuntu-ruby27:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nCurses
      run: sudo apt-get install libncursesw5 libncursesw5-dev libncurses5-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
      env:
        GENERATE_COVERAGE: 1
        TERM: xterm
        
  test-macos-ruby27:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nCurses
      run: brew install ncurses
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
      env:
        TERM: xterm
